#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=lib/_common.sh
source "$ROOT_DIR/lib/_common.sh"
ctt_load_distro_adapter

# Policy 200.4 — les host keys SSH de l'image source doivent être supprimées
# avant sysprep/generalize pour empêcher la réutilisation entre VMs.
# CONTEXTE : ce test est valide sur l'IMAGE généralisée mais pas sur une VM
# en cours d'exécution (cloud-init régénère les keys au 1er boot).
# On accepte le test seulement quand CTT_VALIDATE_GENERALIZED=1 est défini.
if [[ "${CTT_VALIDATE_GENERALIZED:-0}" != "1" ]]; then
  ctt_warn "SSH host keys removed — test skipped (running VM, keys regenerated by cloud-init). Set CTT_VALIDATE_GENERALIZED=1 to enforce."
  exit 0
fi
ctt_remote_check_false "Provisioning artifacts: SSH host keys removed" \
  'if ls /etc/ssh/ssh_host_*_key >/dev/null 2>&1; then echo true; else echo false; fi'
